### ISSUE TITLE
doesnt work with pure functions

### ISSUE THREAD

**Issue by noahehall** [milankinen/livereactload#122]
``` 
//blah.jsx
import React from 'react';
const ResponseTimes = () => {
  return (<div>hello</div> );
};
export default ResponseTimes;
```

console logs
```
Patch module    :: /some/dir/blah.jsx 
LiveReactload :: Patching complete
```

but the changes are not applied

**Comment by noahehall** [comment]
fixed by upgrading to livereactload@2.3.0-rc1

**Comment by milankinen** [comment]
Nice! I recommend using `livereactload@2.3.0-rc7` since it contains a lot of bug fixes and is more stable than rc1.

**Comment by saadq** [comment]
I seem to still have this issue. I've tried both `livereactload@2.3.0-rc7` and `livereactload@3.0.0`, but the reloading doesn't seem to work if I use the stateless functional component syntax. 

Example:

```javascript
import React from 'react'
import { Input } from '../materialize'

const Profile = () => (
  <div>
    <h2>Personal Information</h2>
    <Input classes='col s12' name='full-name' icon='person' />
    <Input classes='col s6' name='email' icon='email' />
    <Input classes='col s6' name='phone-number' icon='phone' />
  </div>
)

export default Profile
```

I get two warnings if I make a change (like removing the `h2` tag):

    <Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically. See https://github.com/reactjs/react-redux/releases/tag/v2.0.0 for the migration instructions.

    Warning: [react-router] You cannot change <Router routes>; it will be ignored

However, it still says `LiveReactload :: Reload complete!` at the end, even though the reload didn't work. 

If I change the component to the ES2015 class syntax:

```javascript
import React, { Component } from 'react'
import { Input } from '../materialize'

class Profile extends Component {
  render () {
    return (
      <div>
        <h2>Personal Information</h2>
        <Input classes='col s12' name='full-name' icon='person' />
        <Input classes='col s6' name='email' icon='email' />
        <Input classes='col s6' name='phone-number' icon='phone' />
      </div>
    )
  }
}

export default Profile
```

And now if I make a change (like removing the `h2`), it livereloads without any issue and there are no warnings in the console. 

This is a server-side rendered app if that makes any difference.
